Get http://localhost:3000/bill/3

###
POST http://localhost:3000/bill
Content-Type: application/json

{
  "uid": 3,
  "orderDetail": [
    {
      "pr_id": 10,
      "sl": 2
    },
    {
      "pr_id": 4,
      "sl": 3
    }
  ]
}

###
Get http://localhost:3000/bill/user/3

###
Get http://localhost:3000/bill/1
###

Patch http://localhost:3000/bill/3
Content-Type: application/json

{
  "orderDetail":[
    {
      "pr_id": 5,
      "sl": 3
    },
    {
      "pr_id": 4,
      "sl": 3
    }
  ]
}

###
Delete http://localhost:3000/bill/1

###
Get http://localhost:3000/products
###
Post http://localhost:3000/user/login
Content-Type: application/json

{
  "username":"khach_hang_vip_01",
  "password": "vip13"
}

###
Post http://localhost:3000/user
Content-Type: application/json

{
  "username":"sfkdfs",
  "email":"haj@gmail.com"
}