Get http://localhost:3000/bill/3

###
POST http://localhost:3000/bill
Content-Type: application/json

{
  "uid": 3,
  "orderDetail": [
    {
      "pr_id": 10,
      "sl": 2
    },
    {
      "pr_id": 4,
      "sl": 3
    }
  ]
}

###
Get http://localhost:3000/bill/user/3

###
Get http://localhost:3000/bill
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsInVzZXJuYW1lIjoiYWRtaW5fbWluaCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc4NjAzNjExMiwiZXhwIjoxNzg2MTIyNTEyfQ.XlsEbD5yChrGl2ZQWQSDElFNZRjaOAVWLJz3LNWxyRQ
###

Patch http://localhost:3000/bill/3
Content-Type: application/json

{
  "orderDetail":[
    {
      "pr_id": 5,
      "sl": 3
    },
    {
      "pr_id": 4,
      "sl": 3
    }
  ]
}

###
Delete http://localhost:3000/bill/1

###
Get http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsInVzZXJuYW1lIjoiYWRtaW5fbWluaCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc4NjAzMjc5MCwiZXhwIjoxNzg2MTE5MTkwfQ._fiP8inaG4vrIeaUeViz3FNvUCuCvJo78nSCfDuBDfU
###
Post http://localhost:3000/user/login
Content-Type: application/json

{
  "username":"admin_minh",
  "password": "adm123"
}

###
Post http://localhost:3000/user
Content-Type: application/json

{
  "username":"sfkdfs",
  "email":"haj@gmail.com"
}